### ISSUE TITLE
Support printing Korean and Chinese characters

### ISSUE THREAD

**Issue by p-sam** [natinusala/borealis#26]
Linked issue in sys-clk: https://github.com/retronx-team/sys-clk/issues/23

borealis does not seem to display Korean characters (attached screenshots in the linked issue), this is probably due to the fact only the regular and the symbol font is loaded. The solution to solve this can be to load the other fonts returned by `pl`, and add them as a fallback font of the current regular font `nvgAddFallbackFontId(...)`

**Comment by natinusala** [comment]
Fixed by 2ec4957301f702635feac64111dcd212d2a37ec6
