### ISSUE TITLE
New Class: Progress bar as dialog popup

### ISSUE THREAD

**Issue by nadrino** [natinusala/borealis#39]
Hello there :) 

I've been working with borealis to build a GUI for SMM, and I would like to add a progress bar layout while the program is executing something (std::async). I tried different things but it seems I can't use brls::Dialog as a class template to do this. So I was wondering maybe this could be interesting to have a kind of template to display anything (like a progress bar) in the style of brls::Dialog::open().

But if you have a better idea to display a popup progress bar (a bit like tinfoil for example) with what's already existing, it would be great too!

Cheers

**Comment by HookedBehemoth** [comment]
On my project I have a small progress bar for uploads that I put as the content view in a brls::Dialog:
https://github.com/HookedBehemoth/ShareNX/blob/brls/applet/elements/upload_process.hpp
https://github.com/HookedBehemoth/ShareNX/blob/brls/applet/elements/upload_process.cpp

If you want to use that for inspiration feel free.

**Comment by nadrino** [comment]
Thanks man! I'm gonna try that :)

**Comment by natinusala** [comment]
The `Dialog` class is generic and is meant to put anything in the dialog frame.

If you want to extend the library and add a `ProgressDialog` class that allows to easily create a modal loading (like the one in system HOS updates), feel free to PR it :)

**Comment by natinusala** [comment]
Duplicated by #103
