### ISSUE TITLE
get selected value from SelectListItem and block exit button

### ISSUE THREAD

**Issue by D3fau4** [natinusala/borealis#56]
Hello!
is there any way to get a value from any listitem?
if i cant get the value could you make public `unsigned selectedValue;`?
also i need block "+" because when i start the system update i can exit from the app. 
(I don't know if borealis already has that options.)
thanks!

**Comment by natinusala** [comment]
Hello,
What kind of ListItem ?

**Comment by D3fau4** [comment]
this type https://github.com/natinusala/borealis/blob/70bd48cdd1706c5dc6471246dac15fa026cc1f72/example/main.cpp#L85

**Comment by natinusala** [comment]
Yeah it needs to be updated to add an `int getSelectedValue`.

As for disabling + to quit, you can do it with `brls::Application::setGlobalQuit(true)`
