### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by eXhumer** [natinusala/borealis#58]
I noticed that there is a COPYING file at the root of the project (which I presume is because of using skeleton from fincs/hybrid_app). Would it not be a better idea to move that to a separate folder like `licenses/hybrid_app.license`. Reason I ask this is because I got confused about two licenses being provided for the project and had to do some headscratching to figure why the zlib license was present for.

**Comment by natinusala** [comment]
Closed as this issue is solved or made irrelevant by the changes on the `yoga` branch.
