### ISSUE TITLE
Allow users to manage swkbdConfigSetKeySetDisableBitmask 

### ISSUE THREAD

**Issue by H0neyBadger** [natinusala/borealis#72]
Hello, 
I think the borealis embedded swkbd is pretty cool.
unfortunately I'm using '/' for my project and this option is locked by default in borealis.
https://github.com/natinusala/borealis/blob/d5ba2eabc0b61a85075a37c21469e3cde5c6bae6/library/lib/swkbd.cpp#L65

I would like to propose a PR, but since swkbd flags are only known by the __SWITCH__ version,
I do not know how to properly implement this without altering the linux compatibility.
do you have any idea on how to proceed ?
thank you a lot

**Comment by natinusala** [comment]
Hey there !

The answer would be to abstract out the swkbd capabilities in a new enum / bitmask, directly in borealis. Then, add a parameter for that in openForText and its friends. Finally, add a way to customize the capabilities on the different ListItems.

**Comment by H0neyBadger** [comment]
OK I will make a PR for this.
Thank you for your guidance.

**Comment by H0neyBadger** [comment]
thank you a lot
