### ISSUE TITLE
Pressing dpad buttons at the same time can result in multiple cursors

### ISSUE THREAD

**Issue by riperiperi** [natinusala/borealis#74]
![image](https://user-images.githubusercontent.com/6294155/99092735-6fd7cd00-25c9-11eb-92ff-7ffb5c2e0e1a.png)
Easiest to notice when using microsoft's unforgivable 360 dpad. If you try extra hard, you can place multiple:

![image](https://user-images.githubusercontent.com/6294155/99093022-dc52cc00-25c9-11eb-88b3-76884f41f2ab.png)

**Comment by Chrscool8** [comment]
Just for information's sake, linking this issue with this PR. Fixed in PR: https://github.com/natinusala/borealis/pull/54

**Comment by natinusala** [comment]
Solved by #54
